<?php

return (new PhpCsFixer\Config())->setRules([
    '@PSR2' => false,
    'array_indentation' => true,
    'array_syntax' => [
        'syntax' => 'short',
    ],
    'blank_line_after_namespace' => true,
    'blank_line_after_opening_tag' => true,
    'blank_line_before_statement' => [
        'statements' => [
            'declare',
            'default',
            'exit',
            'goto',
            'include',
            'include_once',
            'phpdoc',
            'require',
            'require_once',
            'return',
            'switch',
            'try',
            'yield',
            'yield_from',
        ],
    ],
    'braces' => [
        'allow_single_line_closure' => true,
        'position_after_functions_and_oop_constructs' => 'same',
    ],
    'cast_spaces' => true,
    'class_definition' => [
        'single_line' => false,
    ],
    'clean_namespace' => true,
    'combine_consecutive_issets' => false,
    'combine_consecutive_unsets' => false,
    'concat_space' => ['spacing' => 'one'],
    'constant_case' => true,
    'elseif' => true,
    'encoding' => true,
    'function_typehint_space' => true,
    'include' => true,
    'indentation_type' => true,
    'linebreak_after_opening_tag' => true,
    'list_syntax' =>  ['syntax' => 'short'],
    'lowercase_cast' => true,
    'lowercase_keywords' => true,
    'lowercase_static_reference' => true,
    'magic_constant_casing' => true,
    'magic_method_casing' => true,
    'native_function_casing' => true,
    'native_function_type_declaration_casing' => true,
    'no_blank_lines_after_class_opening' => true,
    'no_empty_statement' => true,
    'no_leading_import_slash' => true,
    'no_mixed_echo_print' => ['use' => 'echo'],
    'no_spaces_after_function_name' => true,
    'no_spaces_around_offset' => true,
    'no_spaces_inside_parenthesis' => true,
    'no_trailing_whitespace' => true,
    'no_whitespace_in_blank_line' => true,
    'operator_linebreak' => ['only_booleans' => true],
    'ordered_class_elements' => [
        'order' => [
            'use_trait',
            'case',
            'constant_public',
            'constant_protected',
            'constant_private',
            'property_public',
            'property_protected',
            'property_private',
            'construct',
            'destruct',
            'magic',
            'phpunit',
            'method_abstract',
            'method_public',
            'method_protected',
            'method_private',
        ],
        'sort_algorithm' => 'alpha',
    ],
    'short_scalar_cast' => true,
    'single_blank_line_at_eof' => true,
    'single_class_element_per_statement' => ['elements' => ['const', 'property']],
    'single_quote' => true,
    'ternary_operator_spaces' => true,
    'trailing_comma_in_multiline' => true,
    'whitespace_after_comma_in_array' => true,
])
    ->setIndent('    ')
    ->setLineEnding("\n")
;
