<?php

declare(strict_types=1);

namespace Cassandra;

/**
 * Global enumeration of all exception codes used throughout the Cassandra library.
 * Each exception class has its own prefix based on its namespace or class name in uppercase.
 * 
 * Next free code: 1308
 */
enum ExceptionCode: int {
    // Compression\Exception (COMPRESSION_)
    case COMPRESSION_CHECKSUM_DECODE_FAILURE = 1064;
    case COMPRESSION_CHECKSUM_MISMATCH = 1065;
    case COMPRESSION_DECODE_FAILURE = 1067;
    case COMPRESSION_ILLEGAL_VALUE = 1072;
    case COMPRESSION_INPUT_OVERFLOW = 1073;
    case COMPRESSION_INVALID_MAGIC = 1075;
    case COMPRESSION_INVALID_VERSION = 1078;
    case COMPRESSION_OUTPUT_OVERFLOW = 1079;
    case COMPRESSION_OUTPUT_UNDERFLOW = 1080;

    // Exception\ConnectionException - (CON_)
    case CON_AUTH_FAILED = 1005;
    case CON_AUTH_INVALID_NODE_IMPLEMENTATION = 1006;
    case CON_AUTH_MISSING_CREDENTIALS = 1007;
    case CON_AUTO_PREPARE_ORIGINAL_NOT_QUERY = 1303;
    case CON_AUTO_PREPARE_UNEXPECTED_RESPONSE = 1306;
    case CON_AUTO_PREPARE_UNEXPECTED_RESPONSE_REEXECUTE = 1304;
    case CON_AUTO_PREPARE_UNEXPECTED_RESULT_TYPE = 1302;
    case CON_CANNOT_READ_RESPONSE_HEADER = 1008;
    case CON_COMPRESSION_NOT_SUPPORTED = 1009;
    case CON_EXECUTE_UNEXPECTED_RESPONSE = 1010;
    case CON_INVALID_OPCODE_TYPE = 1012;
    case CON_NOT_CONNECTED = 1013;
    case CON_OPTIONS_UNEXPECTED_RESPONSE = 1014;
    case CON_PREPARE_UNEXPECTED_RESPONSE = 1015;
    case CON_PROTOCOL_VERSION_MISMATCH = 1016;
    case CON_QUERY_UNEXPECTED_RESPONSE = 1017;
    case CON_READY_INVALID_NODE_IMPLEMENTATION = 1018;
    case CON_REPREPARATION_UNEXPECTED_RESPONSE = 1019;
    case CON_REPREPARE_ORIGINAL_NOT_EXECUTE = 1020;
    case CON_REPREPARE_UNEXPECTED_RESPONSE_REEXECUTE = 1021;
    case CON_REPREPARE_UNEXPECTED_RESULT_TYPE = 1022;
    case CON_SERVER_PROTOCOL_UNSUPPORTED = 1023;
    case CON_SET_KEYSPACE_UNEXPECTED_RESPONSE = 1024;
    case CON_STARTUP_UNEXPECTED_RESPONSE = 1025;
    case CON_STREAM_ID_ALREADY_IN_USE = 1305;
    case CON_SYNC_NULL_RESPONSE = 1026;
    case CON_UNABLE_TO_CONNECT_ANY_NODE = 1027;
    case CON_UNEXPECTED_RESPONSE_BATCH_SYNC = 1028;
    case CON_UNKNOWN_ERROR_CODE = 1029;
    case CON_UNKNOWN_EVENT_TYPE = 1030;
    case CON_UNKNOWN_RESPONSE_TYPE = 1031;
    case CON_UNKNOWN_RESULT_KIND = 1032;
    case CON_UNPREPARED_PREV_NO_REQUEST = 1033;
    case CON_UNPREPARED_PREV_NOT_PREPARE_REQUEST = 1034;
    case CON_UNPREPARED_UNEXPECTED_PREV_RESULT_TYPE = 1035;

    // Connection\NodeException (NODE_)
    case NODE_DECODE_COMPUTED_CRC32_FAILED = 1254;
    case NODE_DECODE_FRAME_HEADER_FAILED = 1252;
    case NODE_DECODE_PAYLOAD_CRC32_FAILED = 1260;
    case NODE_DECOMPRESSOR_NOT_INITIALIZED = 1256;
    case NODE_ENCODE_PAYLOAD_CRC32_FAILED = 1259;
    case NODE_INVALID_HEADER_CRC24 = 1253;
    case NODE_INVALID_PAYLOAD_CRC32 = 1255;
    case NODE_INVALID_UNCOMPRESSED_LENGTH = 1257;
    case NODE_PAYLOAD_EXCEEDS_MAX = 1258;
    case NODE_UNSUPPORTED_COMPRESSION = 1251;

    // Request\Exception (REQUEST_)
    case REQUEST_EXECUTE_INVALID_PREVIOUS_RESULT = 1082;
    case REQUEST_EXECUTE_MISSING_RESULT_METADATA_ID = 1083;
    case REQUEST_EXECUTE_PREPARED_STATEMENT_NOT_FOUND = 1084;
    case REQUEST_UNSUPPORTED_OPTION_KEYSPACE = 1085;
    case REQUEST_UNSUPPORTED_OPTION_NOW_IN_SECONDS = 1086;
    case REQUEST_VALUES_NAMES_FOR_VALUES_EXPECTS_ASSOCIATIVE = 1087;
    case REQUEST_VALUES_NAMES_FOR_VALUES_EXPECTS_SEQUENTIAL = 1088;
    case REQUEST_VALUES_UNSUPPORTED_VALUE_TYPE = 1089;

    // Response\Exception (RESPONSE_)
    case RESPONSE_ERROR_INVALID_TYPE = 1090;
    case RESPONSE_EVENT_INVALID_TYPE = 1091;
    case RESPONSE_EVENT_SCHEMA_CHANGE_INVALID_TARGET = 1092;
    case RESPONSE_EVENT_SCHEMA_CHANGE_INVALID_TYPE = 1093;
    case RESPONSE_EVENT_SCHEMA_CHANGE_UNEXPECTED_TARGET_VALUE = 1094;
    case RESPONSE_EVENT_STATUS_CHANGE_INVALID_TYPE = 1095;
    case RESPONSE_EVENT_TOPOLOGY_CHANGE_INVALID_TYPE = 1096;
    case RESPONSE_PREPARED_UNEXPECTED_KIND = 1097;
    case RESPONSE_PSR_GET_DATA_NOT_SUPPORTED = 1098;
    case RESPONSE_PSR_SOURCE_NOT_SET = 1099;
    case RESPONSE_RES_INVALID_KIND_VALUE = 1102;
    case RESPONSE_RES_NOT_PREPARED_RESULT = 1104;
    case RESPONSE_RES_NOT_ROWS_RESULT = 1105;
    case RESPONSE_RES_NOT_SCHEMA_CHANGE_RESULT = 1106;
    case RESPONSE_RES_NOT_SET_KEYSPACE_RESULT = 1107;
    case RESPONSE_RES_NOT_VOID_RESULT = 1108;
    case RESPONSE_RES_PREPARED_CONTEXT_NOT_FOUND = 1109;
    case RESPONSE_RES_PREPARED_DATA_REQUIRED = 1307;
    case RESPONSE_ROWS_INVALID_KEY_INDEX = 1110;
    case RESPONSE_ROWS_INVALID_KEY_TYPE = 1111;
    case RESPONSE_ROWS_INVALID_ROWCLASS = 1112;
    case RESPONSE_ROWS_NO_COLUMN_METADATA = 1113;
    case RESPONSE_ROWS_ROWCLASS_NOT_SUBCLASS = 1114;
    case RESPONSE_SCHEMA_CHANGE_INVALID_TARGET = 1115;
    case RESPONSE_SCHEMA_CHANGE_INVALID_TYPE = 1116;
    case RESPONSE_SCHEMA_CHANGE_UNEXPECTED_KIND = 1117;
    case RESPONSE_SCHEMA_CHANGE_UNEXPECTED_TARGET_VALUE = 1118;
    case RESPONSE_SET_KEYSPACE_UNEXPECTED_KIND = 1119;
    case RESPONSE_SR_INET_PARSE_FAIL = 1120;
    case RESPONSE_SR_INVALID_CONSISTENCY = 1135;
    case RESPONSE_SR_INVALID_INET_LENGTH = 1121;
    case RESPONSE_SR_INVALID_TYPE_DISCRIMINATOR = 1124;
    case RESPONSE_SR_READ_BEYOND_AVAILABLE = 1125;
    case RESPONSE_SR_UNPACK_INT_FAIL = 1129;
    case RESPONSE_SR_UNPACK_LONG_FAIL = 1295;
    case RESPONSE_SR_UNPACK_SHORT_FAIL = 1131;
    case RESPONSE_SR_UNPACK_UUID_FAIL = 1133;
    case RESPONSE_SR_UNPACK_VALUE_LENGTH_FAIL = 1134;
    case RESPONSE_SR_VECTOR_TYPE_NOT_SUPPORTED = 1271;
    case RESPONSE_VOID_UNEXPECTED_KIND = 1136;
    case RESPONSE_WRITE_FAILURE_INVALID_WRITE_TYPE = 1138;
    case RESPONSE_WRITE_TIMEOUT_INVALID_WRITE_TYPE = 1140;

    // Connection\SocketException (SOCKET_)
    case SOCKET_CONNECT_FAILED = 1037;
    case SOCKET_CREATE_FAILED = 1038;
    case SOCKET_INVALID_CONFIG = 1039;
    case SOCKET_NOT_CONNECTED_READ = 1040;
    case SOCKET_NOT_CONNECTED_READ_ONCE = 1041;
    case SOCKET_NOT_CONNECTED_WRITE = 1042;
    case SOCKET_READ_FAILED = 1043;
    case SOCKET_READ_FAILED_CONT = 1044;
    case SOCKET_READ_NO_DATA = 1045;
    case SOCKET_READ_NO_DATA_CONT = 1046;
    case SOCKET_READ_ONCE_FAILED = 1047;
    case SOCKET_READ_ONCE_NO_DATA = 1048;
    case SOCKET_WRITE_FAILED = 1049;

    // Exception\StatementException (STMT_)
    case STMT_UNEXPECTED_PREPARED_RESULT = 1000;
    case STMT_UNEXPECTED_RESULT = 1001;
    case STMT_UNEXPECTED_ROWS_RESULT = 1002;
    case STMT_UNEXPECTED_SCHEMA_CHANGE_RESULT = 1003;
    case STMT_UNEXPECTED_SET_KEYSPACE_RESULT = 1004;

    // Connection\StreamException (STREAM_)
    case STREAM_CONNECT_FAILED = 1050;
    case STREAM_INVALID_CONFIG = 1051;
    case STREAM_NOT_CONNECTED_READ = 1052;
    case STREAM_NOT_CONNECTED_READ_ONCE = 1053;
    case STREAM_NOT_CONNECTED_WRITE = 1054;
    case STREAM_READ_FAILED = 1055;
    case STREAM_READ_ONCE_FAILED = 1056;
    case STREAM_RESET_BY_PEER_READ = 1057;
    case STREAM_RESET_BY_PEER_READ_ONCE = 1058;
    case STREAM_RESET_BY_PEER_WRITE = 1059;
    case STREAM_TIMEOUT_READ = 1060;
    case STREAM_TIMEOUT_READ_ONCE = 1061;
    case STREAM_TIMEOUT_WRITE = 1062;
    case STREAM_WRITE_FAILED = 1063;

    // StringMath\Exception (STRINGMATH_)
    case STRINGMATH_BCMATH_EXTENSION_NOT_LOADED = 1291;
    case STRINGMATH_CALCULATOR_BCMATH_DIVISION_BY_ZERO = 1293;
    case STRINGMATH_CALCULATOR_BCMATH_INVALID_DECIMAL = 1292;
    case STRINGMATH_CALCULATOR_NATIVE_INVALID_CHARACTER = 1261;
    case STRINGMATH_GMP_EXTENSION_NOT_LOADED = 1290;

    // TypeInfo\Exception (TYPEINFO_)
    case TYPEINFO_CUSTOM_INVALID_TYPE = 1237;
    case TYPEINFO_CUSTOM_JAVA_CLASS_NOT_STRING = 1238;
    case TYPEINFO_CUSTOM_MISSING_JAVA_CLASS = 1239;
    case TYPEINFO_CUSTOM_MISSING_TYPE = 1240;
    case TYPEINFO_LIST_INVALID_TYPE = 1227;
    case TYPEINFO_LIST_MISSING_TYPE = 1228;
    case TYPEINFO_LIST_MISSING_VALUETYPE = 1229;
    case TYPEINFO_MAP_INVALID_TYPE = 1230;
    case TYPEINFO_MAP_MISSING_KEYTYPE = 1231;
    case TYPEINFO_MAP_MISSING_TYPE = 1232;
    case TYPEINFO_MAP_MISSING_VALUETYPE = 1233;
    case TYPEINFO_SET_INVALID_TYPE = 1234;
    case TYPEINFO_SET_MISSING_TYPE = 1235;
    case TYPEINFO_SET_MISSING_VALUETYPE = 1236;
    case TYPEINFO_SIMPLE_MISSING_TYPE = 1241;
    case TYPEINFO_SIMPLE_NOT_SIMPLE_TYPE = 1242;
    case TYPEINFO_TUPLE_INVALID_TYPE = 1243;
    case TYPEINFO_TUPLE_MISSING_TYPE = 1244;
    case TYPEINFO_TUPLE_MISSING_VALUETYPES = 1245;
    case TYPEINFO_TUPLE_VALUETYPES_NOT_ARRAY = 1246;
    case TYPEINFO_UDT_INVALID_TYPE = 1247;
    case TYPEINFO_UDT_MISSING_TYPE = 1248;
    case TYPEINFO_UDT_MISSING_VALUETYPES = 1249;
    case TYPEINFO_UDT_VALUETYPES_NOT_ARRAY = 1250;
    case TYPEINFO_VECTOR_INVALID_DIMENSIONS = 1270;
    case TYPEINFO_VECTOR_INVALID_TYPE = 1266;
    case TYPEINFO_VECTOR_MISSING_DIMENSIONS = 1269;
    case TYPEINFO_VECTOR_MISSING_TYPE = 1267;
    case TYPEINFO_VECTOR_MISSING_VALUETYPE = 1268;

    // Exception\TypeNameParserException (TYPENAME_PARSER_)
    case TYPENAME_PARSER_FROZEN_INVALID_PARAM_COUNT = 1272;
    case TYPENAME_PARSER_INVALID_BRACKETS_CLOSING_WITHOUT_OPENING = 1273;
    case TYPENAME_PARSER_INVALID_BRACKETS_MISSING_CLOSING = 1274;
    case TYPENAME_PARSER_INVALID_PARAM_BRACKETS_UNMATCHED_CLOSING = 1275;
    case TYPENAME_PARSER_INVALID_PARAM_BRACKETS_UNMATCHED_OPENING = 1276;
    case TYPENAME_PARSER_LIST_INVALID_PARAM_COUNT = 1277;
    case TYPENAME_PARSER_MAP_INVALID_PARAM_COUNT = 1278;
    case TYPENAME_PARSER_REVERSED_INVALID_PARAM_COUNT = 1279;
    case TYPENAME_PARSER_SET_INVALID_PARAM_COUNT = 1280;
    case TYPENAME_PARSER_SIMPLE_TYPE_CANNOT_BE_FROZEN = 1281;
    case TYPENAME_PARSER_SIMPLE_TYPE_WITH_PARAMETERS = 1282;
    case TYPENAME_PARSER_TUPLE_INVALID_PARAM_COUNT = 1283;
    case TYPENAME_PARSER_UDT_FIELD_KEY_NOT_STRING = 1284;
    case TYPENAME_PARSER_UDT_INVALID_PARAM_COUNT = 1285;
    case TYPENAME_PARSER_UDT_PARAMS_MULTIPLE_COLONS = 1286;
    case TYPENAME_PARSER_VECTOR_DIMENSIONS_NON_NUMERIC = 1287;
    case TYPENAME_PARSER_VECTOR_DIMENSIONS_OUT_OF_RANGE = 1288;
    case TYPENAME_PARSER_VECTOR_INVALID_PARAM_COUNT = 1289;

    // Value\Exception (VALUE_)
    case VALUE_BIGINT_64BIT_REQUIRED = 1142;
    case VALUE_BIGINT_INVALID_VALUE_TYPE = 1143;
    case VALUE_BIGINT_UNPACK_FAILED = 1144;
    case VALUE_BLOB_INVALID_VALUE_TYPE = 1145;
    case VALUE_BOOLEAN_INVALID_VALUE_TYPE = 1146;
    case VALUE_CUSTOM_INVALID_TYPEINFO = 1159;
    case VALUE_CUSTOM_INVALID_VALUE_TYPE = 1160;
    case VALUE_CUSTOM_TYPEINFO_REQUIRED = 1161;
    case VALUE_DATE_INVALID_STRING_FORMAT = 1163;
    case VALUE_DATE_INVALID_VALUE_TYPE = 1164;
    case VALUE_DATE_OUT_OF_RANGE = 1165;
    case VALUE_DECIMAL_INVALID_VALUE_TYPE = 1166;
    case VALUE_DECIMAL_NON_NUMERIC = 1167;
    case VALUE_DECIMAL_UNPACK_FAILED = 1168;
    case VALUE_DOUBLE_INVALID_VALUE_TYPE = 1169;
    case VALUE_DOUBLE_UNPACK_FAILED = 1170;
    case VALUE_DURATION_64BIT_REQUIRED = 1171;
    case VALUE_DURATION_DAYS_INVALID = 1172;
    case VALUE_DURATION_DAYS_OUT_OF_RANGE = 1173;
    case VALUE_DURATION_INVALID_VALUE_TYPE = 1174;
    case VALUE_DURATION_MONTHS_INVALID = 1175;
    case VALUE_DURATION_MONTHS_OUT_OF_RANGE = 1176;
    case VALUE_DURATION_NANOSECONDS_INVALID = 1177;
    case VALUE_DURATION_SIGN_MISMATCH = 1178;
    case VALUE_DURATION_TO_DATEINTERVAL_FAILED = 1179;
    case VALUE_FACTORY_CANNOT_GET_TYPE_OBJECT_FOR_VALUE = 1182;
    case VALUE_FACTORY_CLASS_UNKNOWN_DATA_TYPE = 1183;
    case VALUE_FACTORY_COMPLEX_TYPEINFO_REQUIRED = 1184;
    case VALUE_FACTORY_TYPEDEF_MISSING_TYPE = 1186;
    case VALUE_FACTORY_TYPEDEF_TYPE_NOT_INSTANCE = 1187;
    case VALUE_FACTORY_UNKNOWN_DATA_TYPE = 1188;
    case VALUE_FLOAT32_INVALID_VALUE_TYPE = 1189;
    case VALUE_FLOAT32_UNPACK_FAILED = 1190;
    case VALUE_INET_INVALID_LENGTH = 1299;
    case VALUE_INET_INVALID_VALUE_TYPE = 1191;
    case VALUE_INET_PARSE_FAIL = 1300;
    case VALUE_INET_TO_BINARY_FAILED = 1192;
    case VALUE_INET_TO_STRING_FAILED = 1193;
    case VALUE_INTEGER_INVALID_VALUE_TYPE = 1194;
    case VALUE_INTEGER_OUT_OF_RANGE = 1195;
    case VALUE_INTEGER_UNPACK_FAILED = 1196;
    case VALUE_INVALID_DATA_LENGTH = 1294;
    case VALUE_LIST_INVALID_TYPEINFO = 1147;
    case VALUE_LIST_INVALID_VALUE_TYPE = 1148;
    case VALUE_LIST_TYPEINFO_REQUIRED = 1149;
    case VALUE_MAP_INVALID_MAP_KEY_TYPE = 1301;
    case VALUE_MAP_INVALID_TYPEINFO = 1151;
    case VALUE_MAP_INVALID_VALUE_TYPE = 1152;
    case VALUE_MAP_TYPEINFO_REQUIRED = 1154;
    case VALUE_SET_INVALID_TYPEINFO = 1155;
    case VALUE_SET_INVALID_VALUE_TYPE = 1156;
    case VALUE_SET_TYPEINFO_REQUIRED = 1157;
    case VALUE_SMALLINT_INVALID_VALUE_TYPE = 1197;
    case VALUE_SMALLINT_OUT_OF_RANGE = 1198;
    case VALUE_SMALLINT_UNPACK_FAILED = 1199;
    case VALUE_TIME_64BIT_REQUIRED = 1200;
    case VALUE_TIME_INVALID_DATETIME_STRING = 1201;
    case VALUE_TIME_INVALID_FORMAT = 1202;
    case VALUE_TIME_INVALID_STRING = 1203;
    case VALUE_TIME_INVALID_VALUE_TYPE = 1204;
    case VALUE_TIME_OUT_OF_RANGE = 1205;
    case VALUE_TIMESTAMP_64BIT_REQUIRED = 1207;
    case VALUE_TIMESTAMP_INVALID_VALUE_TYPE = 1208;
    case VALUE_TIMESTAMP_TO_DATETIME_FAILED = 1209;
    case VALUE_TINYINT_INVALID_VALUE_TYPE = 1210;
    case VALUE_TINYINT_OUT_OF_RANGE = 1211;
    case VALUE_TINYINT_UNPACK_FAILED = 1212;
    case VALUE_TUPLE_INVALID_TYPEINFO = 1213;
    case VALUE_TUPLE_INVALID_VALUE_TYPE = 1214;
    case VALUE_TUPLE_TYPEINFO_REQUIRED = 1215;
    case VALUE_UDT_INVALID_TYPEINFO = 1217;
    case VALUE_UDT_INVALID_VALUE_TYPE = 1218;
    case VALUE_UDT_TYPEINFO_REQUIRED = 1219;
    case VALUE_UUID_INVALID_VALUE_TYPE = 1221;
    case VALUE_UUID_UNPACK_FAILED = 1222;
    case VALUE_VARCHAR_INVALID_VALUE_TYPE = 1223;
    case VALUE_VARINT_INVALID_VALUE_TYPE = 1224;
    case VALUE_VARINT_OUT_OF_PHP_INT_RANGE = 1225;
    case VALUE_VARINT_UNPACK_FAILED = 1226;
    case VALUE_VECTOR_INVALID_TYPEINFO = 1262;
    case VALUE_VECTOR_INVALID_VALUE_TYPE = 1263;
    case VALUE_VECTOR_TYPEINFO_REQUIRED = 1264;

    // Exception\VIntCodecException (VINTCODEC_)
    case VINTCODEC_SIGNED_VINT32_OUT_OF_RANGE = 1296;
    case VINTCODEC_UNSIGNED_VINT32_OUT_OF_RANGE = 1297;
    case VINTCODEC_VINT64_UNPACK_FAILED = 1298;
}
