name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring
        tools: composer:v2

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Lint
      run: composer run lint

    - name: Phpstan
      run: composer run phpstan
    
    - name: Psalm
      run: composer run psalm

    - name: PHPUnit unit tests
      run: composer run test:unit

    - name: PHPUnit integration tests
      run: composer run test:integration
