name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.1, 8.2, 8.3, 8.4]
        cassandra: [4.0, 4.1, 5.0]

    name: PHP ${{ matrix.php }} - Cassandra ${{ matrix.cassandra }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring
        tools: composer:v2
        coverage: pcov

    - name: Cache Composer packages
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php }}-

    - name: Install dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - name: Lint
      run: composer run lint

    - name: PHPStan
      run: composer run phpstan
    
    - name: Psalm
      run: composer run psalm

    - name: PHPUnit unit tests
      run: composer run test:unit

    - name: PHPUnit integration tests
      run: CASSANDRA_VERSION=${{ matrix.cassandra }} composer run test:integration
