name: Test

on: [push, pull_request]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.1, 8.2, 8.3, 8.4]

    name: Unit test - PHP ${{ matrix.php }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring
        tools: composer:v2
        coverage: pcov

    - name: Cache Composer packages
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php }}-

    - name: Install dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - name: Lint
      run: composer run lint

    - name: PHPStan
      run: composer run phpstan

    - name: PHPStan tests
      run: composer run phpstan:tests

    - name: Psalm
      run: composer run psalm

    - name: PHPUnit unit tests
      run: composer run test:unit

  integration-test:
    runs-on: ubuntu-latest

    needs: unit-test

    strategy:
      matrix:
        php: ["8.1", "8.2", "8.3", "8.4"]
        cassandra: ["4.0", "4.1", "5.0"]

    name: Integration test - PHP ${{ matrix.php }} - Cassandra ${{ matrix.cassandra }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, bcmath, gmp
        tools: composer:v2
        coverage: pcov

    - name: Cache Composer packages
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php }}-

    - name: Install dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - name: PHPUnit integration tests
      run: CASSANDRA_VERSION=${{ matrix.cassandra }} composer run test:integration

  php-version-compatibility:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        extensions: mbstring, bcmath, gmp
        tools: composer:v2

    - name: Cache Composer packages
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-8.1-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-8.1-

    - name: Install dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - name: Create PHP Compatibility database
      run: vendor/bin/phpcompatinfo db:create

    - name: Initialize PHP Compatibility database
      run: vendor/bin/phpcompatinfo db:init

    - name: Ensure PHP version compatibility with PHP 8.1
      run: scripts/check-php-version.sh
